# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-10-31T08:32:05+00:00

from __future__ import annotations

from typing import *

from fastagency.api.openapi import OpenAPI

from models_ import (
    F30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2SingleMessageInfo,
    F30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2TextMessage,
)

app = OpenAPI(
    title='Infobip OpenAPI Specification',
    description='OpenAPI Specification that contains all public endpoints and webhooks.',
    contact={'name': 'Infobip support', 'email': 'support@infobip.com'},
    version='2.0.504',
    servers=[{'url': 'https://api.infobip.com'}],
)


@app.post(
    '/whatsapp/1/message/text',
    response_model=F30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2SingleMessageInfo,
    description="""Send a text message to a single recipient. Text messages can only be successfully delivered if the recipient has contacted the business within the last 24 hours, otherwise [template message](#channels/whatsapp/send-whatsapp-template-message) should be used. <br/> The API response will not contain the final delivery status, use [Delivery Reports](#channels/whatsapp/receive-whatsapp-delivery-reports) instead.""",
    tags=[
        'channels',
        'whatsapp',
        'whatsapp-outbound-messages',
        'whatsapp-text-and-media-messages',
    ],
)
def send_whatsapp_text_message(
    body: F30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2TextMessage,
) -> F30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2SingleMessageInfo:
    """
    Send WhatsApp text message
    """
    pass
