name: Switch Maintenance Mode

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: "Switch mode: maintenance or working"
        required: true
        default: "working"
        options:
          - "maintenance"
          - "working"

jobs:
  switch_maintenance_mode:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch main branch
        run: git fetch origin main --depth=1

      - name: Checkout main branch
        run: git checkout main

      - name: Copy maintenance.html to tmp directory
        run: |
          mkdir tmp
          cp maintenance.html tmp/

      - name: Get current UTC timestamp and inject into maintenance.html
        run: |
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Current UTC timestamp: ${timestamp}"
          sed -i "s|WRITE_TIMESTAMP_HERE|${timestamp}|" tmp/maintenance.html

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages --depth=1
          git checkout gh-pages

      - name: Prepare for mode switch
        run: | # nosemgrep
          if [ "${{ github.event.inputs.choice }}" == "maintenance" ]; then
            timestamp=$(date +"%Y%m%d%H%M%S")
            mv index.html index_${timestamp}.html
            mv tmp/maintenance.html index.html
          elif [ "${{ github.event.inputs.choice }}" == "working" ]; then
            latest_index=$(ls -t index_*.html | head -1)
            mv $latest_index index.html
          else
            echo "Invalid choice specified"
            exit 1
          fi

      - name: Cleanup temporary directory
        run: rm -rf tmp

      - name: Commit mode switch changes
        uses: stefanzweifel/git-auto-commit-action@v5
